title: "Marwan Charafeddine"
description: "Gameplay Programming & Systems Design"
url: "https://mcharafeddinedev.github.io"
baseurl: ""

remote_theme: just-the-docs/just-the-docs
color_scheme: dark


search_enabled: true
nav_sort: case_insensitive
back_to_top: true
back_to_top_text: "Back to top"


gh_edit_link: false

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

just_the_docs:
  custom_css:
    - assets/css/custom.css

