remote_theme: just-the-docs/just-the-docs

title: "Marwan Charafeddine"
description: "Gameplay Programming & Systems Design | Gold Leaf Interactive"

url: "https://mcharafeddinedev.github.io"
baseurl: ""

color_scheme: dark

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Custom styling for Just the Docs
just_the_docs:
  custom_css:
    - assets/css/custom.css
