title: "Marwan Charafeddine"
logo: "docs/assets/revisedLogoForGitHubPages.png"
description: |
  Game Scripting & Programming |
  mcharafeddinedev@gmail.com 

# Navigation bar setup

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  
# Define the site's navigation
navbar:
  - name: "Home"
    link: "/"
  - name: "Projects"
    link: "/projects"
  - name: "Work History"
    link: "/work-history"
  - name: "My Library"
    link: "/lib"
  - name: "Blog"
  - link: "/blog"

show_downloads: false

