remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# --- basic site settings (recommended) ---
title: "Marwan Charafeddine"
description: "Gameplay Scripting & Systems Design | Gold Leaf Interactive"

# If this repo is USERNAME.github.io, keep baseurl empty.
# If this repo is a PROJECT page, set baseurl to "/repo-name".
url: "https://mcharafeddinedev.github.io"
baseurl: ""

minimal_mistakes_skin: "dark"   # try: "dark", "neon", "contrast", "air"

# --- navigation (Minimal Mistakes expects this) ---


